server:
  port: 8103

spring:
  application:
    name: microservice-provider-user
  datasource:
    first:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/sc_user?allowMultiQueries=true
      username: root
      password: chuchenglong
      max-active: 10
      max-idle: 8
      min-idle: 5
      max-wait: 60000


eureka:
  client:
    serviceUrl:
      defaultZone: http://chuchenglong:8761/eureka/,http://chuchenglong2:8762/eureka/
  instance:
    prefer-ip-address: true