server:
  port: 8002

spring:
  application:
    name: microservice-consumer-movie

eureka:
  client:
    serviceUrl:
      defaultZone: http://chuchenglong:8761/eureka
  instance:
    prefer-ip-address: true