server:
  port: 8761

eureka:
  instance:
    hostname: chuchenglong
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://chuchenglong:8761/eureka